#!/bin/sh

# allokay
# This program works with hspell.
# If all of the spelling errors noted by "hspell" are actually
# okay words, run this program.

# This program adds all of the "erroneous" words last found by
# hspell (and stored in file ,errs) to the file "okayword".

sed -e 's/^[^:]*://' ,errs >> okayword
sort -u okayword > okayword.srt
mv okayword.srt okayword
