#!/bin/sh

# mkinterl - Make a given .gif image interlaced.
# Making .gif images interlaced is good for Netscape users.
# This is a Unix script.
# It takes one argument, the filename of a gif image.

cat $1 | giftoppm | ppmtogif -interlace > ${1},x
mv ${1},x $1
