#!/bin/sh
# mklinks - create a bunch of symbolic links so that
# the old ".html" filenames silently redirect the user to the
# new ".htm" filenames.
# I've enumerated the filenames, because files newer than this
# would presumably be linked using the ".htm" filenames, and some
# files (quiz responses) are unlikely to get linked to.

ln -s baa1994.htm baa1994.html
ln -s biblio.htm biblio.html
ln -s bnf.htm bnf.html
ln -s comments.htm comments.html
ln -s doduse.htm doduse.html
ln -s download.htm download.html
ln -s dwheeler.htm dwheeler.html
ln -s fini.htm fini.html
ln -s formattm.htm formattm.html
ln -s gmu.htm gmu.html
ln -s help-pt2.htm help-pt2.html
ln -s helpmake.htm helpmake.html
ln -s hot_ada.htm hot_ada.html
ln -s how2comp.htm how2comp.html
ln -s legal.htm legal.html
ln -s lesson1.htm lesson1.html
ln -s lesson10.htm lesson10.html
ln -s lesson11.htm lesson11.html
ln -s lesson12.htm lesson12.html
ln -s lesson13.htm lesson13.html
ln -s lesson14.htm lesson14.html
ln -s lesson15.htm lesson15.html
ln -s lesson16.htm lesson16.html
ln -s lesson17.htm lesson17.html
ln -s lesson18.htm lesson18.html
ln -s lesson2.htm lesson2.html
ln -s lesson3.htm lesson3.html
ln -s lesson4.htm lesson4.html
ln -s lesson5.htm lesson5.html
ln -s lesson6.htm lesson6.html
ln -s lesson7.htm lesson7.html
ln -s lesson8.htm lesson8.html
ln -s lesson9.htm lesson9.html
ln -s local.htm local.html
ln -s lovelace.htm lovelace.html
ln -s lversion.htm lversion.html
ln -s master.htm master.html
ln -s note83.htm note83.html
ln -s notes.htm notes.html
ln -s othert.htm othert.html
ln -s philos.htm philos.html
ln -s s1-1.htm s1-1.html
# ln -s s1-1r1.htm s1-1r1.html
# ln -s s1-1r2.htm s1-1r2.html
# ln -s s1-1r3.htm s1-1r3.html
# ln -s s1-1r4.htm s1-1r4.html
ln -s s1-2.htm s1-2.html
# ln -s s1-2r1.htm s1-2r1.html
# ln -s s1-2r2.htm s1-2r2.html
# ln -s s1-2r3.htm s1-2r3.html
ln -s s1-3.htm s1-3.html
# ln -s s1-3r1.htm s1-3r1.html
# ln -s s1-3r2.htm s1-3r2.html
ln -s s1-f.htm s1-f.html
# ln -s s1-fr1.htm s1-fr1.html
# ln -s s1-fr2.htm s1-fr2.html
# ln -s s1-fr3.htm s1-fr3.html
ln -s s10-1.htm s10-1.html
# ln -s s10-1r1.htm s10-1r1.html
# ln -s s10-1r2.htm s10-1r2.html
ln -s s10-2.htm s10-2.html
ln -s s10-f.htm s10-f.html
ln -s s11-1.htm s11-1.html
ln -s s11-2.htm s11-2.html
# ln -s s11-2r1.htm s11-2r1.html
# ln -s s11-2r2.htm s11-2r2.html
# ln -s s11-2r3.htm s11-2r3.html
ln -s s11-f.htm s11-f.html
# ln -s s11-fr1.htm s11-fr1.html
# ln -s s11-fr2.htm s11-fr2.html
# ln -s s11-fr3.htm s11-fr3.html
ln -s s12-1.htm s12-1.html
ln -s s12-2.htm s12-2.html
# ln -s s12-2r1.htm s12-2r1.html
# ln -s s12-2r2.htm s12-2r2.html
# ln -s s12-2r3.htm s12-2r3.html
ln -s s12-f.htm s12-f.html
ln -s s13-1.htm s13-1.html
# ln -s s13-1r1.htm s13-1r1.html
# ln -s s13-1r2.htm s13-1r2.html
ln -s s13-2.htm s13-2.html
# ln -s s13-2r1.htm s13-2r1.html
# ln -s s13-2r2.htm s13-2r2.html
ln -s s13-3.htm s13-3.html
# ln -s s13-3r1.htm s13-3r1.html
# ln -s s13-3r2.htm s13-3r2.html
# ln -s s13-3r3.htm s13-3r3.html
ln -s s13-4.htm s13-4.html
ln -s s13-f.htm s13-f.html
# ln -s s13-fr1.htm s13-fr1.html
# ln -s s13-fr2.htm s13-fr2.html
ln -s s14-1.htm s14-1.html
# ln -s s14-1r1.htm s14-1r1.html
# ln -s s14-1r2.htm s14-1r2.html
# ln -s s14-1r3.htm s14-1r3.html
ln -s s14-2.htm s14-2.html
# ln -s s14-2r1.htm s14-2r1.html
# ln -s s14-2r2.htm s14-2r2.html
# ln -s s14-2r3.htm s14-2r3.html
# ln -s s14-2r4.htm s14-2r4.html
# ln -s s14-2r5.htm s14-2r5.html
# ln -s s14-2r6.htm s14-2r6.html
ln -s s14-f.htm s14-f.html
# ln -s s14-fr1.htm s14-fr1.html
# ln -s s14-fr2.htm s14-fr2.html
# ln -s s14-fr3.htm s14-fr3.html
# ln -s s14-fr4.htm s14-fr4.html
# ln -s s14-fr5.htm s14-fr5.html
# ln -s s14-fr6.htm s14-fr6.html
ln -s s15-1.htm s15-1.html
ln -s s15-f.htm s15-f.html
ln -s s16-1.htm s16-1.html
# ln -s s16-1r1.htm s16-1r1.html
# ln -s s16-1r2.htm s16-1r2.html
# ln -s s16-1r3.htm s16-1r3.html
ln -s s16-2.htm s16-2.html
ln -s s16-f.htm s16-f.html
# ln -s s16-fr1.htm s16-fr1.html
# ln -s s16-fr2.htm s16-fr2.html
ln -s s17-1.htm s17-1.html
# ln -s s17-1r1.htm s17-1r1.html
# ln -s s17-1r2.htm s17-1r2.html
# ln -s s17-1r3.htm s17-1r3.html
ln -s s17-2.htm s17-2.html
# ln -s s17-2r1.htm s17-2r1.html
# ln -s s17-2r2.htm s17-2r2.html
# ln -s s17-2r3.htm s17-2r3.html
ln -s s17-3.htm s17-3.html
# ln -s s17-3r1.htm s17-3r1.html
# ln -s s17-3r2.htm s17-3r2.html
# ln -s s17-3r3.htm s17-3r3.html
# ln -s s17-3r4.htm s17-3r4.html
ln -s s17-4.htm s17-4.html
# ln -s s17-4r1.htm s17-4r1.html
# ln -s s17-4r2.htm s17-4r2.html
# ln -s s17-4r3.htm s17-4r3.html
# ln -s s17-4r4.htm s17-4r4.html
ln -s s17-f.htm s17-f.html
ln -s s18-1.htm s18-1.html
# ln -s s18-1r1.htm s18-1r1.html
# ln -s s18-1r2.htm s18-1r2.html
# ln -s s18-1r3.htm s18-1r3.html
ln -s s18-2.htm s18-2.html
# ln -s s18-2r1.htm s18-2r1.html
# ln -s s18-2r2.htm s18-2r2.html
ln -s s18-3.htm s18-3.html
# ln -s s18-3r1.htm s18-3r1.html
# ln -s s18-3r2.htm s18-3r2.html
# ln -s s18-3r3.htm s18-3r3.html
ln -s s18-4.htm s18-4.html
# ln -s s18-4r1.htm s18-4r1.html
# ln -s s18-4r2.htm s18-4r2.html
# ln -s s18-4r3.htm s18-4r3.html
# ln -s s18-4r4.htm s18-4r4.html
# ln -s s18-4r5.htm s18-4r5.html
ln -s s18-5.htm s18-5.html
# ln -s s18-5r1.htm s18-5r1.html
# ln -s s18-5r2.htm s18-5r2.html
ln -s s18-6.htm s18-6.html
# ln -s s18-6r1.htm s18-6r1.html
# ln -s s18-6r2.htm s18-6r2.html
ln -s s18-f.htm s18-f.html
ln -s s19-1.htm s19-1.html
ln -s s2-1.htm s2-1.html
# ln -s s2-1r1.htm s2-1r1.html
# ln -s s2-1r2.htm s2-1r2.html
# ln -s s2-1r3.htm s2-1r3.html
ln -s s2-2.htm s2-2.html
# ln -s s2-2r1.htm s2-2r1.html
# ln -s s2-2r2.htm s2-2r2.html
ln -s s2-3.htm s2-3.html
# ln -s s2-3r1.htm s2-3r1.html
# ln -s s2-3r2.htm s2-3r2.html
# ln -s s2-3r3.htm s2-3r3.html
# ln -s s2-3r4.htm s2-3r4.html
ln -s s2-4.htm s2-4.html
# ln -s s2-4r1.htm s2-4r1.html
# ln -s s2-4r2.htm s2-4r2.html
# ln -s s2-4r3.htm s2-4r3.html
# ln -s s2-4r4.htm s2-4r4.html
ln -s s2-f.htm s2-f.html
# ln -s s2-fr1.htm s2-fr1.html
# ln -s s2-fr2.htm s2-fr2.html
ln -s s3-1.htm s3-1.html
# ln -s s3-1r1.htm s3-1r1.html
# ln -s s3-1r2.htm s3-1r2.html
ln -s s3-2.htm s3-2.html
# ln -s s3-2r1.htm s3-2r1.html
# ln -s s3-2r2.htm s3-2r2.html
ln -s s3-3.htm s3-3.html
# ln -s s3-3r1.htm s3-3r1.html
# ln -s s3-3r2.htm s3-3r2.html
ln -s s3-f.htm s3-f.html
# ln -s s3-fr1.htm s3-fr1.html
# ln -s s3-fr2.htm s3-fr2.html
# ln -s s3-fr3.htm s3-fr3.html
ln -s s4-1.htm s4-1.html
# ln -s s4-1r1.htm s4-1r1.html
# ln -s s4-1r2.htm s4-1r2.html
# ln -s s4-1r3.htm s4-1r3.html
ln -s s4-2.htm s4-2.html
# ln -s s4-2r1.htm s4-2r1.html
# ln -s s4-2r2.htm s4-2r2.html
# ln -s s4-2r3.htm s4-2r3.html
ln -s s4-f.htm s4-f.html
# ln -s s4-fr1.htm s4-fr1.html
# ln -s s4-fr2.htm s4-fr2.html
# ln -s s4-fr3.htm s4-fr3.html
ln -s s5-1.htm s5-1.html
# ln -s s5-1r1.htm s5-1r1.html
# ln -s s5-1r2.htm s5-1r2.html
# ln -s s5-1r3.htm s5-1r3.html
ln -s s5-2.htm s5-2.html
# ln -s s5-2r1.htm s5-2r1.html
# ln -s s5-2r2.htm s5-2r2.html
# ln -s s5-2r3.htm s5-2r3.html
# ln -s s5-2r4.htm s5-2r4.html
# ln -s s5-2r5.htm s5-2r5.html
ln -s s5-f.htm s5-f.html
# ln -s s5-fr1.htm s5-fr1.html
# ln -s s5-fr2.htm s5-fr2.html
# ln -s s5-fr3.htm s5-fr3.html
ln -s s6-1.htm s6-1.html
# ln -s s6-1r1.htm s6-1r1.html
# ln -s s6-1r2.htm s6-1r2.html
# ln -s s6-1r3.htm s6-1r3.html
ln -s s6-2.htm s6-2.html
# ln -s s6-2r1.htm s6-2r1.html
# ln -s s6-2r2.htm s6-2r2.html
# ln -s s6-2r3.htm s6-2r3.html
ln -s s6-3.htm s6-3.html
# ln -s s6-3r1.htm s6-3r1.html
# ln -s s6-3r2.htm s6-3r2.html
ln -s s6-4.htm s6-4.html
ln -s s6-5.htm s6-5.html
ln -s s6-6.htm s6-6.html
# ln -s s6-6r1.htm s6-6r1.html
# ln -s s6-6r2.htm s6-6r2.html
# ln -s s6-6r3.htm s6-6r3.html
ln -s s6-f.htm s6-f.html
# ln -s s6-fr1.htm s6-fr1.html
# ln -s s6-fr2.htm s6-fr2.html
# ln -s s6-fr3.htm s6-fr3.html
ln -s s7-1.htm s7-1.html
# ln -s s7-1r1.htm s7-1r1.html
# ln -s s7-1r2.htm s7-1r2.html
# ln -s s7-1r3.htm s7-1r3.html
ln -s s7-2.htm s7-2.html
# ln -s s7-2r1.htm s7-2r1.html
# ln -s s7-2r2.htm s7-2r2.html
# ln -s s7-2r3.htm s7-2r3.html
ln -s s7-3.htm s7-3.html
# ln -s s7-3r1.htm s7-3r1.html
# ln -s s7-3r2.htm s7-3r2.html
# ln -s s7-3r3.htm s7-3r3.html
# ln -s s7-3r4.htm s7-3r4.html
ln -s s7-4.htm s7-4.html
# ln -s s7-4r1.htm s7-4r1.html
# ln -s s7-4r2.htm s7-4r2.html
# ln -s s7-4r3.htm s7-4r3.html
ln -s s7-5.htm s7-5.html
# ln -s s7-5r1.htm s7-5r1.html
# ln -s s7-5r2.htm s7-5r2.html
# ln -s s7-5r3.htm s7-5r3.html
ln -s s7-6.htm s7-6.html
ln -s s7-f.htm s7-f.html
# ln -s s7-fr1.htm s7-fr1.html
# ln -s s7-fr2.htm s7-fr2.html
# ln -s s7-fr3.htm s7-fr3.html
# ln -s s7-fr4.htm s7-fr4.html
ln -s s8-1.htm s8-1.html
# ln -s s8-1r1.htm s8-1r1.html
# ln -s s8-1r2.htm s8-1r2.html
# ln -s s8-1r3.htm s8-1r3.html
ln -s s8-2.htm s8-2.html
# ln -s s8-2r1.htm s8-2r1.html
# ln -s s8-2r2.htm s8-2r2.html
# ln -s s8-2r3.htm s8-2r3.html
# ln -s s8-2r4.htm s8-2r4.html
ln -s s8-3.htm s8-3.html
# ln -s s8-3r1.htm s8-3r1.html
# ln -s s8-3r2.htm s8-3r2.html
# ln -s s8-3r3.htm s8-3r3.html
# ln -s s8-3r4.htm s8-3r4.html
ln -s s8-4.htm s8-4.html
# ln -s s8-4r1.htm s8-4r1.html
# ln -s s8-4r2.htm s8-4r2.html
ln -s s8-5.htm s8-5.html
# ln -s s8-5r1.htm s8-5r1.html
# ln -s s8-5r2.htm s8-5r2.html
# ln -s s8-5r3.htm s8-5r3.html
ln -s s8-f.htm s8-f.html
# ln -s s8-fr1.htm s8-fr1.html
# ln -s s8-fr2.htm s8-fr2.html
# ln -s s8-fr3.htm s8-fr3.html
ln -s s9-1.htm s9-1.html
# ln -s s9-1r1.htm s9-1r1.html
# ln -s s9-1r2.htm s9-1r2.html
# ln -s s9-1r3.htm s9-1r3.html
ln -s s9-2.htm s9-2.html
# ln -s s9-2r1.htm s9-2r1.html
# ln -s s9-2r2.htm s9-2r2.html
# ln -s s9-2r3.htm s9-2r3.html
ln -s s9-3.htm s9-3.html
ln -s s9-f.htm s9-f.html
# ln -s s9-fr1.htm s9-fr1.html
# ln -s s9-fr2.htm s9-fr2.html
# ln -s s9-fr3.htm s9-fr3.html
ln -s skip1-1.htm skip1-1.html
ln -s tutors.htm tutors.html
ln -s userg.htm userg.html
