#!/bin/sh

# wcout: take output of "wc" and make it human-readable.

# lines words bytes

sed -e 's/^ *//' \
    -e 's/  */ lines, /' \
    -e 's/\(lines, [^ ]*\)  */\1 words, and /' \
    -e 's/$/ bytes/'

