#!/bin/sh
./sweet-filter < tests > ,results
if cmp -s correct ,results
then
 echo "Correct results! (File ,results identical to file correct!)"
else
 echo "File correct differs from ,results:"
 diff -u correct ,results
fi
