#!/bin/sh

echo '<sect2>'
echo "<title>File $1</title>"
echo '<para>'
echo '<programlisting>'
echo '<![CDATA['

# sed -e 's/\&/\&amp;/g' -e 's/</\&lt;/g' -e 's/>/\&gt;/g' < $1

cat $1

echo ']]>'
echo '</programlisting>'
echo '</para>'
echo '</sect2>'
