# Makefile by David A. Wheeler

all:
	echo "Type make alang.tar to make tar file."

# Create a tar file for the demo implementation of alang concepts.

alang.tar:
	tar cvfb alang.tar 20 makefile README COPYING \
	   linkit/InputFormat linkit/README \
	   linkit/makefile linkit/*.[ch] linkit/test* \
	   compile/*.[chyl] compile/makefile compile/test* \
	   compile/README
